import type { Metadata } from "next";
import "./globals.css";
import ScrollTop from "@/components/core/ScrollTop";

export const metadata: Metadata = {
  title: "CSE:BUBT - Bangladesh University of Business and Technology",
  description: "Generated by tech sand developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* Scroll Top */}
        <ScrollTop />
      </body>
    </html>
  );
}
